[package]
authors = ["Oleksandr Kovalchuk <anxolerd@outlook.com>"]
name = "game-of-life"
version = "0.1.0"

[dependencies]
piston = "0.32.0"
piston2d-graphics = "0.21.1"
piston2d-opengl_graphics = "0.45.0"
pistoncore-glutin_window = "0.38.0"
